DROP FUNCTION organization_get_by_id(IN orgId UUID);
DROP FUNCTION organization_get_user_role(IN userId UUID, IN orgId UUID, OUT role VARCHAR(16));
DROP FUNCTION organization_list(IN l_limit INTEGER, IN l_offset INTEGER);
DROP FUNCTION organization_list_by_user(IN userId UUID, IN l_limit INTEGER, IN l_offset INTEGER);
DROP FUNCTION organization_create(IN userId UUID, IN orgName VARCHAR(256));
DROP FUNCTION organization_user_add(IN orgId UUID, IN userId UUID, IN userRole VARCHAR(16));
DROP PROCEDURE organization_user_remove(orgId UUID, userId UUID);
DROP FUNCTION organization_user_list(IN orgId UUID, IN l_limit INTEGER, IN l_offset INTEGER);
DROP FUNCTION organization_team_list(IN orgId UUID, IN l_limit INTEGER, IN l_offset INTEGER);
DROP FUNCTION organization_team_create(IN orgId UUID, IN teamName VARCHAR(256));
DROP FUNCTION organization_team_user_role(IN userId UUID, IN orgId UUID, IN teamId UUID);