version: "2"
linters:
  disable:
    - errcheck
  settings:
    govet:
      disable:
        - printf
    staticcheck:
      checks:
        - all
        - -QF1008  # could remove embedded field from selector
        - -ST1005  # error strings should not end with punctuation or newlines
        - -QF1004  # could use strings.ReplaceAll instead
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
