linters:
  disable:
    - errcheck
  enable:
    - goimports
    - gofmt
linters-settings:
  govet:
    disable:
      # printf: non-constant format string in call to fmt.Errorf (govet)
      # showing up since golangci-lint version 1.60.1
      - printf