version: "2"
linters:
  disable:
    - errcheck
    - QF1008 # could remove embedded field from selector (staticcheck)
    - ST1005 # error strings should not end with punctuation or newlines (staticcheck)
    - QF1004 # could use strings.ReplaceAll instead (staticcheck)
  settings:
    govet:
      disable:
        - printf
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
