name: lint
on:
  workflow_call:

permissions:
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  # pull-requests: read

jobs:
  go:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ "1.26" ]

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # v6.1.0
        with:
          go-version: ${{ matrix.go }}
      #          cache: false

      - name: Copy swagger docs dummy file and Create dummy ui/dist/index.html
        run: mkdir ui/dist && touch ui/dist/index.html

      - name: golangci-lint
        uses: golangci/golangci-lint-action@82606bf257cbaff209d206a39f5134f0cfbfd2ee # v9.2.1
        with:
          # Require: The version of golangci-lint to use.
          # When `install-mode` is `binary` (default) the value can be v1.2 or v1.2.3 or `latest` to use the latest version.
          # When `install-mode` is `goinstall` the value can be v1.2.3, `latest`, or the hash
          version: v2.10
          args: --timeout 3m0s

  ui:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ "24.17" ]

    steps:
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
        with:
          node-version: ${{ matrix.node-version }}

      - name: Check out code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - run: npm ci
        working-directory: ui
      - run: npm run prettier
        working-directory: ui
      - run: npm ci
        working-directory: e2e
      - run: npm run prettier
        working-directory: e2e